/**:
  ros__parameters:
    neck_up_limit   : 2048
    neck_down_limit : 1350
    neck_left_limit : 2650
    neck_right_limit: 1350
    robot_number    : 2

/neck_node:
  ros__parameters:
    neck_activate: true

    x_p_gain: 0.5
    y_p_gain: 0.4

/control:
  ros__parameters:
    body_activate : true
    walk_counter  : 80   #20

/decision_node:
  ros__parameters:
    FALL_ACCEL_TH: 8.5
    FALSES_FALLEN_TH: 30

/image_node:
  ros__parameters:
    get_image: true
    img_qlty: 70