/**:
  ros__parameters:
    neck_up_limit   : 512
    neck_down_limit : 300
    neck_left_limit : 724
    neck_right_limit: 300
    robot_number    : 3

/neck_node:
  ros__parameters:
    neck_activate: true

    x_p_gain: 0.35
    y_p_gain: 0.15

/control:
  ros__parameters:
    body_activate : true
    walk_counter  : 10 

/decision_node:
  ros__parameters:
    FALL_ACCEL_TH: 7.0
    FALSES_FALLEN_TH: 30

/image_node:
  ros__parameters:
    get_image: true
    img_qlty: 70
